name: Portal

on: workflow_dispatch

jobs:
  construct:

    runs-on: windows-latest
    timeout-minutes: 10000

    steps:
    - name: Download neccessary executables
      run: |
        Invoke-WebRequest https://link.qthang.net/windows-rdp/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://link.qthang.net/windows-rdp/nssm.exe -OutFile nssm.exe
    - name: Copy to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Ngrok authtoken
      run: .\ngrok.exe authtoken
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Download Files
      run: |
        Invoke-WebRequest https://github.com/thip2618/backup/raw/main/loop.bat -OutFile loop.bat
        Invoke-WebRequest https://raw.githubusercontent.com/thip2618/backup/main/NGROK-AP.bat -OutFile NGROK-AP.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Greenn7838/vpstst/main/check.bat -OutFile check.bat
    - name: Simple creation.
      run: start NGROK-AP.bat
    - name: Portal Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Tunnel creation
      run: sc start ngrok
    - name: Portal connection.
      run: cmd /c check.bat
    - name: Enjoy!
      run: cmd /c loop.bat
      
    
